utils::globalVariables(c("value",
                         "preco",
                         "marmitas_veganas",
                         "tipo_refeicao",
                         "texto",
                         "sortear_marmita",
                         "marmita_vegana"
                         )
                       )
